[build]
builder = "RAILPACK"
watchPattern = "src/**"

[deploy]
startCommand = "npx prisma generate && npx prisma db push --skip-generate && npm run db:seed && npm run start"
healthcheckPath = "/api/auth/session"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
