[build]
builder = "RAILPACK"
watchPattern = "src/**"

[deploy]
startCommand = "NODE_ENV=production bun run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
